### PR TITLE
Add SOC ( state of charge )

### PR DESCRIPTION
**Pull request by cedric222**
Add SOC ( state of charge )

### CODE REVIEW

**Comment by gboudreau** [comment]
Thanks.

**Comment by Raiden38** [comment]
Hi!

Can you give me more details on the New value? What is the difference between soc and battery remaining? And time to green?

Thanks!

Ps: on parle français aussi si tu préfère...

Envoyé de mon iPhone

**Comment by gboudreau** [comment]
From what I know, SOC is a percentage, and is only available on 2013+ models. Older modes don't show a percentage, and thus won't return a value for SOC.

**Comment by Raiden38** [comment]
Is it the same as battery remaining / total battery * 100?

And what is time to green?

Envoyé de mon iPhone

**Comment by gboudreau** [comment]
No idea, I have a MY 2011 which doesn't return a SOC.

**Comment by cedric222** [comment]
Hi,

SOC is more precise than battery remaining / total battery for me (battery remaining go every ten)
(I have a European 2016 30kwh Leaf)

I add some messages from my car

 Response: {"status":200,"message":"success","BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"Apr 29, 2016 06:00 PM","BatteryStatus":{"BatteryChargingStatus":"NOT_CHARGING","BatteryCapacity":"240","BatteryRemainingAmount":"140","BatteryRemainingAmountWH":"16000","BatteryRemainingAmountkWH":"","SOC":{"Value":"55"}},"PluginState":"CONNECTED","CruisingRangeAcOn":"104000","CruisingRangeAcOff":"107000","TimeRequiredToFull":{"HourRequiredToFull":"19","MinutesRequiredToFull":"30"},"TimeRequiredToFull200":{"HourRequiredToFull":"11","MinutesRequiredToFull":"30"},"TimeRequiredToFull200_6kW":{"HourRequiredToFull":"4","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2016\/04\/29 16:01","TargetDate":"2016\/04\/29 16:00"}}

and with a very very few battery :-(
[2016-04-30 13:31:37][nissan_leaf_connect][DEBUG] : [NissanConnect] Response: {"status":200,"message":"success","BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"Apr 30, 2016 01:30 PM","BatteryStatus":{"BatteryChargingStatus":"NORMAL_CHARGING","BatteryCapacity":"240","BatteryRemainingAmount":"20","BatteryRemainingAmountWH":"1440","BatteryRemainingAmountkWH":"","SOC":{"Display":"---"}},"PluginState":"CONNECTED","TimeRequiredToFull200":{"HourRequiredToFull":"18","MinutesRequiredToFull":"30"},"NotificationDateAndTime":"2016\/04\/30 11:31","TargetDate":"2016\/04\/30 11:30"}}

and with a full charge
 [NissanConnect] Response: {"status":200,"message":"success","BatteryStatusRecords":{"OperationResult":"START","OperationDateAndTime":"May  1, 2016 04:00 PM","BatteryStatus":{"BatteryChargingStatus":"NOT_CHARGING","BatteryCapacity":"240","BatteryRemainingAmount":"240","BatteryRemainingAmountWH":"29040","BatteryRemainingAmountkWH":"","SOC":{"Value":"100"}},"PluginState":"NOT_CONNECTED","CruisingRangeAcOn":"221000","CruisingRangeAcOff":"232000","NotificationDateAndTime":"2016\/05\/01 14:00","TargetDate":"2016\/05\/01 14:00"}}


>  time to green? 
I try to create myself a better estimation for charging with a french "green-up plug" (220 / 10A). But after some test the TimeRequiredToFull200 seems good enought, I revert this change.

**Comment by Raiden38** [comment]
Hi

This must be something for the european version, as it’s not available in North America. There is a few fields that are not available also. Here is the current reading of my car:

{ ["LastUpdated"]=> string(16) "2016-05-01 13:00" ["PluggedIn"]=> bool(true) ["ChargingMode"]=> string(12) "NOT_CHARGING" ["Charging"]=> bool(false) ["BatteryCapacity"]=> int(12) ["BatteryRemainingAmount"]=> int(12) ["BatteryRemainingAmountWH"]=> NULL ["BatteryRemainingAmountkWH"]=> NULL ["SOC"]=> NULL ["TimeRequiredToFull"]=> NULL ["TimeRequiredToFull200"]=> NULL ["TimeRequiredToFull200_6kW"]=> NULL ["CruisingRangeAcOn"]=> float(142.032) ["CruisingRangeAcOff"]=> float(146.336) ["CruisingRangeUnit"]=> string(2) "km" ["RemoteACRunning"]=> bool(false) ["RemoteACLastChanged"]=> string(16) "2016-05-01 21:35" ["ACStartStopURL"]=> NULL ["ACDurationBatterySec"]=> int(900) ["ACDurationPluggedSec"]=> int(7200) }

**Comment by cedric222** [comment]
@gboudreau : FYI, I use your php in a jeedom plugin -> https://market.jeedom.fr/index.php?v=d

**Pull request merged**
